version: '3.7'

services:
  php-fpm:
    build:
      context: ../../php-fpm
      dockerfile: Dockerfile
    container_name: tyrun-pilulka-php-fpm
    restart: always
    volumes:
      #app files
      - ./../../../app:/var/www:rw
      #config files
      - ./../../php-fpm/conf/conf.d:/usr/local/etc/php/conf.d:ro
      - ./../../php-fpm/conf/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    working_dir: /var/www
    command: "php-fpm"
    depends_on:
      - redis

  nginx:
    build:
      context: ../../nginx
      dockerfile: Dockerfile
    container_name: tyrun-pilulka-nginx
    restart: always
    volumes:
      #app files
      - ./../../../app:/var/www:rw
      #nginx config files
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./../../nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      #logs volume
      - legend-nginx-logs:/var/log/nginx:rw
    ports:
      - 80:80
      - 443:443
    depends_on:
      - php-fpm

  redis:
    build:
      context: ../../redis
      dockerfile: Dockerfile
    container_name: tyrun-pilulka-redis
    restart: always
    volumes:
      #data volume
      - legend-redis:/data

volumes:
  legend-nginx-logs:
  legend-redis:
